# Generated by Django 5.1.3 on 2024-11-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dictionary_wordpair_delete_dictionarydata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpair',
            name='dictionary',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='WordPair',
        ),
    ]
