# Generated by Django 5.1.3 on 2024-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='data',
            field=models.TextField(),
        ),
    ]
