# Generated by Django 5.1.3 on 2024-11-20 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_dictionary_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='data',
        ),
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_word', models.CharField(max_length=255)),
                ('replace_word', models.CharField(max_length=255)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_pairs', to='home.dictionary')),
            ],
        ),
    ]
